FROM node:alpine as builder

WORKDIR /client
RUN npm install -g @angular/cli
COPY ./package.json .
RUN npm install
COPY . .
RUN npm rebuild node-sass
RUN npm run build

FROM nginx
# EXPOSE 5000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /client/dist/client /usr/share/nginx/html